Commit from shell alias at 08/13/23 02:34:43 AM

diff --git a/bin/dnfs b/bin/dnfs
--- a/bin/dnfs
+++ b/bin/dnfs
@@ -1,56 +1,68 @@
-#!/usr/bin/env bash
+#!/usr/bin/bash
+# vlk's dnfs, a program to search dnf for packages in a TUI
+set -euo pipefail
+IFS=$'\n\t'
 
-[[ "$(realpath "$(which dnf)")" != *'dnf-3' ]] && echo "Error, dnfs does not work with dnf5 yet!" && exit 1
+filterstr='(^$|\.i686|\.src|..-debuginfo|..-debugsource|^Last metadata expiration check|^Available Packages)'
+cosmetic_sedstr='s/-devel\./\x1b[1m-devel\x1b[0m\./g
+s/\.x86_64$/\.\x1b[92mx86_64\x1b[0m/g
+s/\.noarch$/\.\x1b[93mnoarch\x1b[0m/g'
 
-fzf_query="${@:- }"
-
-package_installed () {
-    local return_value=""
-    for i in ${installed_packages}; do
-        if [[ "$i" == "$1" ]]; then
-            local return_value=''
-        else
-            local return_value="$i"
-        fi
-    done
-    echo "$return_value"
-}
-
-dnf_list_function () {
-    local selected="$(printf "$packages" | fzf -q "$fzf_query")"
-    if [ -z "$selected" ]; then
-        echo "no"
-    #elif dnf list --installed | grep "^$selected " &>/dev/null; then
-    #    return
-    else
-        echo "$selected"
-    fi
-}
-
-echo "searching..."
-
-packages="$(dnf list --available -C | tail -n +2 | grep -v -e '\.i686' -e '\.src' -e '..-debuginfo' -e '..-debugsource' | grep '\.' | cut -d ' ' -f 1)"
-
-while :; do
-    package=$(dnf_list_function)
-    if [ -z "$package" ]; then
-        printf "[\e[1;31mERROR\e[0m] Selected package is already installed! Choose another? \e[1m[y/n]\e[0m (y) > "
-        read answer
-        [[ "$answer" == 'n' ]] && exit 1
-    elif [[ "$package" == 'no' ]]; then
-        printf "[\e[1;31mERROR\e[0m] No package selected! Exiting..."
-        exit 1
-    else
-        break
-    fi
-done
-
-dnf info -C "$package"
-
-if sudo -vn &> /dev/null; then
-    sudo dnf install "$package"
-else
-    printf "\e[1m[\e[;31mSUDO\e[0m\e[1m]\e[0m Install '$package'? \e[1m[y/n]\e[0m (y) > "
-    read install_answer
-    [[ "$install_answer" == 'y' ]] && sudo dnf install "$package"
+if [[ "$(realpath "$(command -v dnf)")" != *'dnf-3' ]]; then
+    echo "Error, ${0##*/} does not work with dnf5 yet!"
+    exit 1
 fi
+if command -v fzf &>/dev/null; then
+    true
+else
+    echo "Error, please install fzf!"
+    echo -e "\x1b[1msudo dnf install fzf\x1b[0m"
+fi
+
+fzfcmd="$(echo -e "fzf --ansi --header='Use \x1b[1mTAB\x1b[0m to select multiple packages' --multi")"
+if [ -n "${1:-}" ]; then
+    fzfcmd="$fzfcmd -q '$*'"
+fi
+
+echo 'Searching...'
+# grep '\.' |
+packages="$(dnf list --available -C | grep -Ev "$filterstr" | cut -d ' ' -f 1)"
+
+selected_packages="$(
+    echo "$packages" | sed "$cosmetic_sedstr" | sh -c "$fzfcmd"
+)"
+
+(
+    echo "You are about to install the following packages"
+    for i in $selected_packages; do
+        dnf info -C "$i"
+        printf '%s\n' '' ''
+    done
+) | ${PAGER:-less}
+
+if sudo -vn &>/dev/null; then
+    true
+else
+    echo -e '\x1b[1m[\x1b[91mSUDO Required\x1b[0m\x1b[1m]\x1b[0m'
+    echo 'Installing the following packages'
+    printf '%s\n' $selected_packages | sed "$cosmetic_sedstr"
+    echo -n 'Are you sure you want to install these packages? '
+    while true; do
+        printf '\x1b[1m[y/n]\x1b[0m (n) > '
+        read install_answer
+        case "$install_answer" in
+        '')
+            continue
+            ;;
+        'y')
+            break
+            ;;
+        *)
+            echo -e "\x1b[0mOperation aborted"
+            exit 1
+            ;;
+        esac
+    done
+fi
+
+sudo dnf install $selected_packages
