Commit from dotfiles.sh at 10/11/23 02:05:24 AM

diff --git a/bin/psa b/bin/psa
--- a/bin/psa
+++ b/bin/psa
@@ -1,109 +1,205 @@
-#!/usr/bin/bash
-set -euo pipefail
-# IFS=$'\n\t'
-IFS=$' \n\t'
+#!/usr/bin/perl
+# psa.pl, by vlk
+# https://github.com/REALERvolker1/homescripts
+use strict;
+use warnings;
+use v5.36;
 
-for i in pidstat fzf lscolors realpath dircolors pstree; do
-    if ! command -v "$i" &>/dev/null; then
-        echo "Missing dependency command '$i'" >&2
-        exit 1
-    fi
-done
-[ -z "${LS_COLORS:-}" ] && eval "$(dircolors -b <(dircolors -p))"
-
-exe_color="[$(echo "$LS_COLORS" | tr -s ':' '\n' | grep -m 1 -oP 'ex=\K[^:]*')m"
-
-arg_colorizer() {
-    local i i_key i_val join firstarg
-    local -a output=()
-    for i in "$@"; do
-        if [ -z "${firstarg:-}" ]; then
-            if [ ! -e "$i" ] && command -v "$i" &>/dev/null && [[ "$i" != *'/'* ]]; then
-                i="${exe_color:-[1m}$i"
-                firstarg='y'
-                # i="[1m${i}[0m"
-            fi
-        fi
-        if [[ "$i" == *'='* ]]; then
-            i_key="${i%%=*}"
-            i_val="${i#*=}"
-            join='='
-        else
-            i_key="$i"
-            i_val=''
-            join=''
-        fi
-        if [ -e "$i_key" ]; then
-            i_key="$(lscolors "$i_key")"
-        elif [ -e "$i_val" ]; then
-            i_val="$(lscolors "$i_val")"
-        fi
-        output+=("${i_key}${join}${i_val}")
-        # echo -n "[0m${output}[0m "
-    done
-    printf '[0m%s[0m ' "${output[@]}"
+sub checkcmd {
+    my @nullcmds = ();
+    foreach (@_) {
+        push( @nullcmds, $_ )
+          unless system("command -v $_ >/dev/null 2>&1") == 0;
+    }
+    return @nullcmds;
 }
 
-PIDSTAT='pidstat --human -lRtU -p'
-export S_COLORS=always
-declare -A actions=(
-    [stat]='1: Get statistics'
-    [tree]='2: Print process tree'
-    [kill]='3: Kill process'
-)
+# sudo dnf install sysstat fzf coreutils lscolors
+# system("command -v $_ >/dev/null 2>&1")
+# my @failed_deps =
+#   grep { checkcmd($_) != 0 } ( "ps", "pidstat", "fzf", "dircolors", "pstree" );
+my @failed_deps = checkcmd( "ps", "pidstat", "fzf", "dircolors", "pstree" );
 
-ps="$(
-    ps -eo pid,comm,args |
-        tr -s '[:blank:]' ' ' |
-        sed -E 's/^\s+([0-9]+) ([^ ]+)(\s+([^ ]+))?/[0m[1;33m\1[0m [1;94m\2[0m[32m\3/g' |
-        fzf --ansi --preview-window='down,25%' --header-lines=1 --preview="$PIDSTAT \$"'(echo {} | grep -oP "^\\s*\\K[^ ]*")' -q "${1:-}"
-)"
-[ -z "${ps:-}" ] && exit 1
+die
+"Install the following binaries using your distribution's package manager: \n\e[1m"
+  . join( " ", @failed_deps )
+  . "\e[0m\n"
+  . "(eg: sudo dnf install sysstat fzf coreutils lscolors)\n"
+  unless scalar(@failed_deps) == 0;
 
-pid="${ps%% *}"
-tmpps="${ps#* }"
-comm="${tmpps%% *}"
-tmpps="${tmpps#* }"
-args="${tmpps# *}"
+my $lscolors = "lscolors";
+unless ( checkcmd($lscolors) == 0 ) {
+    warn "binary 'lscolors' not found. Falling back to 'echo'\n";
+    $lscolors = "echo";
+    warn
+"You can install it with '\e[0;1;92mcargo\e[0;1m install \e[0;1;93mlscolors\e[0m'\n"
+      if ( checkcmd("cargo") == 0 );
+}
 
-commstr="[1mPID:[0m $pid
-[1mName:[0m $comm
-[0m$(arg_colorizer $args)[0m"
+unless ( defined $ENV{"LS_COLORS"} ) {
+    print "LS_COLORS is not set. Setting them now.\n";
 
-case "$(printf '%s\n' "${actions[@]}" | sort | fzf --ansi --preview-window='down,25%' --preview="echo '$commstr'")" in
-"${actions[stat]}")
-    exec sh -c "$PIDSTAT $pid"
-    ;;
-"${actions[tree]}")
-    pstree -sp "$pid"
-    # parent=''
-    # declare -a children
-    # found=''
-    # for i in $(ps -eo pid,comm --forest --no-headers); do
-    #     if [[ "$i" == *"$pid"* ]]; then
-    #         i="$(tput bold)$i$(tput sgr0)"
-    #         found=1
-    #     fi
-    #     if [[ "$i" == *'\_'* ]]; then
-    #         children+=("$i")
-    #     else
-    #         [ -n "$found" ] && break
-    #         parent="$i"
-    #         children=()
-    #     fi
-    # done
-    # printf '%s\n' "$parent" "${children[@]}"
-    ;;
-"${actions[kill]}")
-    echo "Are you sure you want to kill process ${pid}?"
-    echo "$ps"
-    echo -n '[y/N] > '
-    read -r answer
-    [ "$answer" != y ] && exit 0
-    kill "$pid"
-    ;;
-*)
-    echo "Error, please select a valid action!" >&2
-    exit 1
-    ;;
-esac
+    # C-shell output is easier to parse through
+    my $dir_colors = `dircolors -c`;
+    die "Error finding dir colors! Exit code: $?\n" unless $? == 0;
+    $dir_colors =~ s/^setenv LS_COLORS '([^']+)'/$1/;
+
+    # $dir_colors =~ s/'$//;
+    print $dir_colors;
+    $ENV{"LS_COLORS"} = $dir_colors;
+}
+
+# my ($dir_color) = $ENV{"LS_COLORS"} =~ /:di=([^:]+)/;
+
+my @procs      = ();
+my %colorpaths = ();
+my $output_str = "";
+
+my $path_disp_color = "\e[0;1;91m";
+print "Formatting processes...\n";
+foreach ( split( "\n", `ps -eo '%p\t%c\t' -o exe -o '\t%a'` ) ) {
+    my ( $pid, $name, $comm, $args ) = split( /\s*\t\s*/, $_ );
+
+    # This makes sure that you always see the full command path and args
+
+    # Skip kernel processes. Killing these would be foolish
+    next if ( $args =~ /^\[[^\]]*\]$/ );
+    $pid =~ s/\s*//;
+
+    # next if ( $pid =~ /\s*PID/ );
+    $name =~ s/^\s+|\s+$//g;
+    $comm =~ s/^\s+|\s+$//g;
+    $args =~ s/^\s+|\s+$|\n//g;
+
+    # You don't need to see the same thing twice if you don't have to
+    if ( $args =~ /^\s*$|^$comm$/ ) {
+        $args = $comm;
+    }
+    elsif ( $args =~ /^\s*$comm/ ) {
+        $args =~ s/^\s*\Q$comm\E\s*//;
+        $args = "$comm $args";
+    }
+    elsif ( $comm =~ /^\s*-\s*$/ ) { }
+    else {
+        # $args = "($comm) $args";
+        $args =~ s/^\s*([^\s]+)/\($1\) $comm/;
+    }
+    my $procstr      = "$pid\t$name\t$args";
+    my @colored_args = ();
+    if ( $args =~ /<defunct>$/ ) {
+        $name =~ s/\s*<defunct>\s*//;
+        push( @colored_args, "\e[93m<defunct> $args\e[0m" );
+    }
+    else {
+# I want to see LS_COLORS. I spent a damn long time on my config and so I need to feel like it meant something
+        foreach ( split( /\s+|\t+/, $args ) ) {
+            unless ( $_ =~ /\/+/ ) {
+                push( @colored_args, "\e[32m$_\e[0m" );
+                next;
+            }
+            my ($parsed) = $_ =~ /(\/[^\/][^\s]+)/;       # |file:\/\/[^\s]+
+            my $colorparsed = $parsed;
+
+            if ( defined $colorpaths{$parsed} ) {
+                $colorparsed = $colorpaths{$parsed};
+            }
+            elsif ( $parsed =~ /"/ ) {
+                $colorparsed = "${path_disp_color}$parsed\e[0m";
+            }
+            elsif ( $parsed =~ /^\/app/ ) {
+                $colorparsed = "\e[0;1;95m$parsed\e[0m";
+            }
+            else {
+                my ($shencoded) = $parsed =~ s/"//g;
+                $colorparsed = `$lscolors "$parsed"`;
+                $colorpaths{$parsed} = $colorparsed;
+            }
+            $colorparsed =~ s/\e\[0m/$path_disp_color/g;
+            $colorparsed =~ s/\n/\e\[0m/g;
+            $_           =~ s/\Q$parsed\E/$colorparsed/g;
+            push( @colored_args, "\e[1;32m$_\e[0m" );
+        }
+    }
+    $output_str .=
+      "\e[1;93m$pid\e[0;96m\t$name\e[0m\t" . join( " ", @colored_args ) . "\n";
+    push( @procs, $procstr );
+}
+$ENV{"S_COLORS"} = "always";
+
+# $output_str =~ s/^\s*\n$//;
+chomp($output_str);
+my $pidstat = "pidstat --human -lRtU -p";
+
+if ( defined $ENV{"PSAPL_DEBUGFILE"} ) {
+    warn "Printing output to debugfile at $ENV{'PSAPL_DEBUGFILE'}\n";
+    open( my $debugfile, ">", $ENV{"PSAPL_DEBUGFILE"} )
+      or die "Could not open file: $!";
+    print $debugfile $output_str;
+    close $debugfile;
+}
+
+# my $chosen =
+# `fzf --ansi --preview-window='down,25%' --header-lines=1 --preview=\"$pidstat \\\$(echo {} | sed 's|\\\t.*||')\" <<< "$output_str"`;
+my $chosen =
+`echo "$output_str" | fzf --ansi --preview-window='down,25%' --header-lines=1 --preview=\"$pidstat \\\$(echo {} | sed 's|\\\t.*||')\"`;
+die "Error, no process selected!\n"
+  unless ( defined $chosen && $chosen =~ /[^\s]+/ );
+
+chomp($chosen);
+
+# $chosen =~ s/\n//g;
+
+my ( $pid, $name, $args ) = split( /\s*\t\s*/, $chosen );
+
+my $owner = `ps -o user -p $pid`;
+$owner =~ s/^USER|\n+//g;
+
+# https://github.com/REALERvolker1/homescripts
+my %actions = (
+    stat => "1: \e[94mGet statistics (pidstat)\e[0m",
+    echo => "2: \e[95mPrint process details\e[0m",
+    tree => "3: \e[92mGet process tree (pstree)\e[0m",
+    kill => "4: \e[91mKill process (kill)\e[0m",
+);
+delete $actions{"kill"} if ( $owner ne $ENV{"USER"} );
+
+my $action_str = join(
+    "\n",
+    sort {
+        my ($anum) = $a =~ /^(\d+)/;
+        my ($bnum) = $b =~ /^(\d+)/;
+        $anum <=> $bnum;
+    } values %actions
+);
+
+my $pidstats = `$pidstat '$pid'`;
+chomp($pidstats);
+
+my $action =
+`echo '$action_str' | fzf --ansi --preview-window='down,50%' --preview=\"echo '$pidstats'\"`;
+$action =~ s/^([0-9]+).*\n/$1/;
+
+my $cmd_output = "PID: $pid\nNAME: $name\nARGS: $args";
+if ( $action =~ /^\s*$/ ) {
+    $cmd_output = "No action specified. Exiting";
+}
+elsif ( $actions{"stat"} =~ /^$action/ ) {
+    $cmd_output = `$pidstat '$pid'`;
+}
+elsif ( $actions{"echo"} =~ /^$action/ ) { }
+elsif ( $actions{"tree"} =~ /^$action/ ) {
+    $cmd_output = `pstree -sp '$pid'`;
+}
+elsif ( $actions{"kill"} =~ /^$action/ ) {
+    print
+"Are you sure you want to \e[1;91mKILL\e[0m this process?\n$cmd_output\n[y/N] > ";
+    my $ans = <STDIN>;
+    chomp($ans);
+    system("kill $pid") if ( $ans eq "y" );
+    $cmd_output = "Received answer: '$ans'";
+}
+else {
+    $cmd_output = "Error, invalid action specified!";
+}
+chomp($cmd_output);
+print "$cmd_output\n";
