Commit from shell alias at 09/05/23 09:40:04 PM

diff --git a/bin/startx b/bin/startx
--- a/bin/startx
+++ b/bin/startx
@@ -1,223 +1,132 @@
-#!/usr/bin/sh
-# This is a slightly nicer implementation of startx written by vlk for use on Fedora.
+#!/usr/bin/bash
+# a startx implementation, by vlk
+# intended to be interchangeable with Fedora's startx
+# shellcheck disable=SC1091 disable=SC1090
 
-unset DBUS_SESSION_BUS_ADDRESS
-unset SESSION_MANAGER
-userclientrc="${XINITRC:-$HOME/.xinitrc}"
-sysclientrc=/etc/X11/xinit/xinitrc
-
-userserverrc="${XSERVERRC:-$HOME/.xserverrc}"
-sysserverrc=/etc/X11/xinit/xserverrc
-defaultclient=xterm
-defaultserver=/usr/bin/Xorg
-defaultclientargs=""
-defaultserverargs=""
-defaultdisplay=""
-clientargs=""
-serverargs=""
-vtarg=""
-enable_xauth=1
-
-#export XAUTHORITY="${XAUTHORITY:-$XDG_RUNTIME_DIR/Xauthority}"
-#export ERRFILE="${ERRFILE:-$XDG_RUNTIME_DIR/xsession-errors}"
-
-# Automatically determine an unused $DISPLAY
-d=0
-while true; do
-    [ -e "/tmp/.X$d-lock" -o -S "/tmp/.X11-unix/X$d" ] ||
-        grep -q "/tmp/.X11-unix/X$d" "/proc/net/unix" ||
-        break
-    d=$(($d + 1))
-done
-defaultdisplay=":$d"
-unset d
-
-xsessionfolder="${XDG_RUNTIME_DIR:-/tmp}/xorg-$defaultdisplay"
-mkdir -p "$xsessionfolder"
-export XAUTHORITY="$xsessionfolder/Xauthority"
-export SERVERAUTH="$xsessionfolder/serverauth.$$"
-export ERRFILE="$xsessionfolder/xsession-errors"
-
-whoseargs="client"
-while [ x"$1" != x ]; do
-    case "$1" in
-    # '' required to prevent cpp from treating "/*" as a C comment.
-    /''* | \./''*)
-        if [ "$whoseargs" = "client" ]; then
-            if [ x"$client" = x ] && [ x"$clientargs" = x ]; then
-                client="$1"
-            else
-                clientargs="$clientargs $1"
-            fi
-        else
-            if [ x"$server" = x ] && [ x"$serverargs" = x ]; then
-                server="$1"
-            else
-                serverargs="$serverargs $1"
-            fi
-        fi
-        ;;
-    --)
-        whoseargs="server"
+debug_mode=''
+my_tty="$(tty)"
+if [ "$TERM" != 'linux' ] && [ -z "${debug_mode:-}" ]; then
+    case "${my_tty:-}" in
+    '/dev/tty'*)
+        true
         ;;
     *)
-        if [ "$whoseargs" = "client" ]; then
-            clientargs="$clientargs $1"
-        else
-            # display must be the FIRST server argument
-            if [ x"$serverargs" = x ] &&
-                expr "$1" : ':[0-9][0-9]*$' >/dev/null 2>&1; then
-                display="$1"
-            else
-                serverargs="$serverargs $1"
-            fi
-        fi
+        echo "Invalid tty '$(tty)', running in debug mode" >&2
+        debug_mode=1
         ;;
     esac
-    shift
-done
-
-# process client arguments
-if [ x"$client" = x ]; then
-    client=$defaultclient
-
-    # For compatibility reasons, only use startxrc if there were no client command line arguments
-    if [ x"$clientargs" = x ]; then
-        if [ -f "$userclientrc" ]; then
-            client=$userclientrc
-        elif [ -f "$sysclientrc" ]; then
-            client=$sysclientrc
-        fi
-    fi
 fi
+[ -f "$HOME/.profile" ] && . "$HOME/.profile"
 
-# if no client arguments, use defaults
-if [ x"$clientargs" = x ]; then
-    clientargs=$defaultclientargs
+declare -a server_args client_args
+
+if [ -f "${XSERVERRC:-$HOME/.xserverrc}" ]; then
+    xserver_bin="${XSERVERRC:-$HOME/.xserverrc}"
+else
+    xserver_bin=/usr/bin/Xorg
 fi
-
-# process server arguments
-if [ x"$server" = x ]; then
-    server=$defaultserver
-
-    # When starting the defaultserver start X on the current tty to avoid
-    # the startx session being seen as inactive:
-    # "https://bugzilla.redhat.com/show_bug.cgi?id=806491"
-    tty=$(tty)
-    if expr "$tty" : '/dev/tty[0-9][0-9]*$' >/dev/null; then
-        tty_num=$(echo "$tty" | grep -oE '[0-9]+$')
-        vtarg="vt$tty_num -keeptty"
-    fi
-
-    # For compatibility reasons, only use xserverrc if there were no server command line arguments
-    if [ x"$serverargs" = x -a x"$display" = x ]; then
-        if [ -f "$userserverrc" ]; then
-            server=$userserverrc
-        elif [ -f "$sysserverrc" ]; then
-            server=$sysserverrc
-        fi
-    fi
-fi
-
-# if no server arguments, use defaults
-if [ x"$serverargs" = x ]; then
-    serverargs=$defaultserverargs
-fi
-
-# if no vt is specified add vtarg (which may be empty)
-have_vtarg="no"
-for i in $serverargs; do
-    if expr "$i" : 'vt[0-9][0-9]*$' >/dev/null; then
-        have_vtarg="yes"
-    fi
-done
-if [ "$have_vtarg" = "no" -a x"$vtarg" != x ]; then
-    serverargs="$serverargs $vtarg"
-    # Fedora specific mod to make X run as non root
-    export XORG_RUN_AS_USER_OK=1
-fi
-
-# if no display, use default
-if [ x"$display" = x ]; then
-    display=$defaultdisplay
-fi
-
-if [ x"$enable_xauth" = x1 ]; then
-    if [ x"$XAUTHORITY" = x ]; then
-        XAUTHORITY=$HOME/.Xauthority
-        export XAUTHORITY
-    fi
-
-    removelist=
-
-    # set up default Xauth info for this machine
-    case $(uname) in
-    Linux*)
-        if [ -z "$(hostname --version 2>&1 | grep GNU)" ]; then
-            hostname=$(hostname -f)
-        else
-            hostname=$(hostname)
-        fi
-        ;;
-    *)
-        hostname=$(hostname)
-        ;;
-    esac
-
-    authdisplay=${display:-:0}
-
-    mcookie=$(/usr/bin/mcookie)
-
-    if test x"$mcookie" = x; then
-        echo "Couldn't create cookie"
-        exit 1
-    fi
-    dummy=0
-
-    # create a file with auth information for the server. ':0' is a dummy.
-    xserverauthfile="$SERVERAUTH"
-    trap "rm -f '$xserverauthfile'" HUP INT QUIT ILL TRAP KILL BUS TERM
-    xauth -q -f "$xserverauthfile" <<EOF
-add :$dummy . $mcookie
-EOF
-
-    serverargs=${serverargs}" -auth "${xserverauthfile}
-
-    # now add the same credentials to the client authority file
-    # if '$displayname' already exists do not overwrite it as another
-    # server may need it. Add them to the '$xserverauthfile' instead.
-    for displayname in $authdisplay $hostname$authdisplay; do
-        authcookie=$(xauth list "$displayname" |
-            sed -n "s/.*$displayname[[:space:]*].*[[:space:]*]//p") 2>/dev/null
-        if [ "z${authcookie}" = "z" ]; then
-            xauth -q <<EOF
-add $displayname . $mcookie
-EOF
-            removelist="$displayname $removelist"
-        else
-            dummy=$(($dummy + 1))
-            xauth -q -f "$xserverauthfile" <<EOF
-add :$dummy . $authcookie
-EOF
-        fi
+if command -v "${1%% *}" &>/dev/null || [ -x "${1%% *}" ]; then
+    for i in $1; do
+        client_args+=("$i")
+    done
+else
+    for i in "$XINITRC" \
+        "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xinitrc" \
+        "$HOME/.xinitrc"; do
+        [ ! -x "$i" ] && continue
+        client_args+=("$i")
     done
 fi
+# printf '%s\n' "${client_args[@]}"
 
-xinit "$client" $clientargs -- "$server" $display $serverargs
+# determine unused display
+for ((i = 0; i < 9999; i++)); do
+    [ -e "/tmp/.X${i}-lock" ] ||
+        [ -S "/tmp/.X11-unix/X${i}" ] ||
+        grep -q "/tmp/.X11-unix/X${i}" "/proc/net/unix" ||
+        break
+done
+display=":${i}"
 
-retval=$?
+# determine paths to stuff
+xsessionfolder="${XDG_RUNTIME_DIR:-/tmp}/xorg-$display"
+export XAUTHORITY="$xsessionfolder/Xauthority"
+export ERRFILE="$xsessionfolder/xsession-errors"
 
-if [ x"$enable_xauth" = x1 ]; then
-    if [ x"$removelist" != x ]; then
-        xauth remove $removelist
+# Fedora specific mod to make X run as non root
+export XORG_RUN_AS_USER_OK=1
+export XDG_SESSION_TYPE=x11
+declare -a xauth_args xinit_args
+
+xauth_args+=(
+    "add"
+    "$display"
+    'MIT-MAGIC-COOKIE-1'
+    "$(mcookie)"
+)
+
+server_args+=(
+    "$xserver_bin"
+    "$display"
+    "vt${my_tty##*[!0-9]}"
+    "-keeptty"
+    "-noreset"
+    "-auth"
+    "$XAUTHORITY"
+)
+
+# xinit_args+=(
+#     "$xclient_bin" # client, clientargs, --, server, display, serverargs
+#     "--"
+#     "$xserver_bin"
+#     "$display"
+#     "vt${my_tty##*[!0-9]}"
+#     "-keeptty"
+#     "-noreset"
+#     "-auth"
+#     "$XAUTHORITY"
+# )
+
+_cleanup() {
+    if [ "$server" ] && kill -0 "$server" 2>/dev/null; then
+        kill "$server"
+        wait "$server"
+        xorg=$?
     fi
-    if [ x"$xserverauthfile" != x ]; then
-        rm -f "$xserverauthfile"
+    if ! stty "$original_stty"; then
+        stty sane
     fi
-fi
-
-if command -v deallocvt >/dev/null 2>&1; then
+    xauth remove "$display"
+    rm -r "$xsessionfolder"
     deallocvt
-fi
+    echo -e "\nCleaned up X server\n" >&2
+}
 
-exit $retval
+echo xauth "${xauth_args[@]}"
+echo "${server_args[@]}"
+# echo xinit "${xinit_args[@]}"
+[ -n "${debug_mode:-}" ] && exit 0
+
+mkdir "$xsessionfolder"
+touch -- "$XAUTHORITY"
+touch -- "$ERRFILE"
+original_stty="$(stty --save)"
+xauth "${xauth_args[@]}"
+
+trap '_cleanup; exit "${xorg:-0}"' EXIT
+echo trapped exit
+for signal in HUP INT QUIT TERM; do
+    trap "_cleanup; trap - $signal EXIT; kill -s $signal $$" "$signal"
+done
+echo trapped signal loop
+trap 'DISPLAY=$display "${client_args[@]}" & wait "$!"' USR1
+echo trapped client stuff
+# trap '_cleanup' HUP INT QUIT ILL TRAP BUS TERM
+(trap '' USR1 && exec "${server_args[@]}") &
+server=$!
+echo started server
+wait "$server"
+# xinit "${xinit_args[@]}" >"$ERRFILE"
+# retval=$?
+# _cleanup
+# exit "$retval"
