Commit from shell alias at 09/11/23 03:09:55 PM

diff --git a/bin/vlk-sensible-screenshot b/bin/vlk-sensible-screenshot
--- a/bin/vlk-sensible-screenshot
+++ b/bin/vlk-sensible-screenshot
@@ -1,3 +1,33 @@
-#!/usr/bin/dash
+#!/usr/bin/bash
 
+declare -A _vss_cmd
+ss_dir="$HOME/Pictures/Screenshots"
+# ss_path_grimblast="$HOME/Pictures/Screenshots/grimblast-$(date +"%y-%m-%d_%H-%M-%S").png"
+# ss_path_swappy="- | swappy -f -" # edit config savedir location in ~/.config/swappy/config
+# ss_path_flameshot="$HOME/Pictures/Screenshots/flameshot-$(date +"%y-%m-%d_%H-%M-%S").png"
 
+if [ -n "${WAYLAND_DISPLAY}" ]; then
+    if [ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]; then
+        if ! command -v grimblast &>/dev/null; then
+            echo "Error, could not find grimblast"
+            exit 2
+        fi
+        _vss_cmd[1]="grimblast --freeze save area"
+        _vss_cmd[2]="grimblast --cursor --freeze save output"
+        _vss_cmd[3]="grimblast --cursor --freeze save screen"
+        if command -v swappy &>/dev/null; then
+            for i in {1..3}; do
+                declare "_vss_cmd[${i}]=${_vss_cmd[$i]} - | swappy -f -"
+            done
+        else
+            for i in {1..3}; do
+                declare "_vss_cmd[${i}]=${_vss_cmd[$i]} '$ss_dir/grimblast-$(date +"%y-%m-%d_%H-%M-%S").png'"
+            done
+        fi
+        # printf '%s\n' "${_vss_cmd[@]}"
+    else
+        notify-send "Error, current wayland desktop '${XDG_CURRENT_DESKTOP:-Unknown}' is not supported!"
+        exit 1
+    fi
+fi
+exec sh -c "${_vss_cmd[$1]}"
