Commit from shell alias at 08/18/23 10:36:43 PM

diff --git a/bin/vlkenv b/bin/vlkenv
--- a/bin/vlkenv
+++ b/bin/vlkenv
@@ -7,7 +7,7 @@
 
 export CURRENT_DISTRO="$(grep -oP '^NAME="\K[^ ]*' /etc/os-release)"
 
-export HOME="${HOME:-/home/vlk}"
+export HOME="${HOME:-/home/$(whoami)}"
 export XDG_CONFIG_HOME="$HOME/.config"
 export XDG_DATA_HOME="$HOME/.local/share"
 export XDG_CACHE_HOME="$HOME/.cache"
@@ -24,13 +24,7 @@ export QT_STYLE_OVERRIDE='kvantum'
 export MOZ_ENABLE_WAYLAND=1
 export UWUFETCH_CACHE_ENABLED=true
 
-#if [ -f "$XDG_CONFIG_HOME/dircolors/generated.sh" ]; then
-#    . "$XDG_CONFIG_HOME/dircolors/generated.sh"
-#elif [ -f "$XDG_CONFIG_HOME/dircolors/dir_colors" ]; then
-#    eval "$(dircolors "$XDG_CONFIG_HOME/dircolors/dir_colors")"
-#fi
-[ -f "$XDG_CONFIG_HOME/dircolors/dir_colors" ] && eval "$(dircolors "$XDG_CONFIG_HOME/dircolors/dir_colors")"
-
+eval "$(dircolors -b "$XDG_CONFIG_HOME/dircolors/dir_colors" || echo 'echo error loading dircolors')"
 export GREP_COLORS="mt=01;91:fn=03;32:ln=33:bn=36:se=35"
 export JQ_COLORS="0;31:0;36:1;36:0;33:1;32:0;37:1;37"
 export SUDO_PROMPT="$(printf "\e[0m\e[1m[\e[31mSUDO\e[0m\e[1m]\e[0m") "
@@ -124,7 +118,7 @@ export NVM_DIR="$XDG_DATA_HOME/nvm"
 export BUN_INSTALL="$XDG_DATA_HOME/bun"
 export DENO_INSTALL="$XDG_DATA_HOME/deno"
 
-temppath="$PATH"
+__vlkenv_temppath="$PATH"
 for i in \
     "/var/lib/flatpak/exports/bin" \
     "${PYTHONUSERBASE:-PYTHONUSERBASE}/bin" \
@@ -132,25 +126,23 @@ for i in \
     "${BUN_INSTALL:-BUN_INSTALL}/bin" \
     "${GOPATH:-GOPATH}/bin" \
     "${CARGO_HOME:-CARGO_HOME}/bin" \
-    "${HOME:=/home/$(whoami)}/.local/bin" \
-    "${CARGO_HOME:-CARGO_HOME}/bin" \
-    "$HOME/bin"
-do
+    "$HOME/.local/bin" \
+    "$HOME/bin"; do
     if [ -d "$i" ]; then
-        case ":$temppath:" in
-            *:"$i":*)
-                continue
-                ;;
-            *)
-                temppath="$i:$temppath"
-                ;;
+        case ":$__vlkenv_temppath:" in
+        *:"$i":*)
+            continue
+            ;;
+        *)
+            __vlkenv_temppath="$i:$__vlkenv_temppath"
+            ;;
         esac
     else
         continue
     fi
 done
 unset i
-export PATH="$temppath"
+export PATH="$__vlkenv_temppath"
 
 unset ICON_TYPE
 __vlkenv_term="${TERM:-}"
@@ -166,6 +158,6 @@ case "$__vlkenv_term" in
     ICON_TYPE='fallback'
     ;;
 esac
-unset __vlkenv_term
 export ICON_TYPE
 
+unset __vlkenv_term __vlkenv_temppath
