Commit from dotfiles.sh at 12/04/23 03:48:17 AM

diff --git a/bin/vlkenv b/bin/vlkenv
--- a/bin/vlkenv
+++ b/bin/vlkenv
@@ -1,157 +1,175 @@
-# shellcheck shell=dash
-# shellcheck disable=2155,2153
+# shellcheck shell=bash disable=2155,2153,1090,1091,2206,2296,2298,2190
 # vim:foldmethod=marker:ft=sh
-# a script by vlk to load environment variables for sh-compatible shells.
+# a script by vlk to load environment variables for bash and zsh shells.
 # Intended to be resilient even if the shell is launched with `env -i`
 
 # unset any safe mode, it is not intended for interactive shells
-set +eu
+set +euo pipefail
 # printenv >~/vlkenvcache
 # add /bin to path just in case
 PATH="${PATH:+$PATH:}/usr/bin"
 
 unset MAILCHECK
-[ "${LANG:-C}" = 'C' ] && export LANG="en_US.UTF-8"
+[[ ${LANG:-C} == C ]] && export LANG='en_US.UTF-8'
+echo -n '[0m'
+export TTY="${TTY:-$(tty)}"
 
 # set the terminal TERM variable to fix shell behavior
-if [ -z "${TERM:-}" ] || tput 2>&1 | grep -q 'unknown terminal'; then
-    case "${TTY:=$(tty)}" in
-    /dev/pts*) TERM='xterm-256color' ;;
-    *) TERM=linux ;;
-    esac
-    echo "TERM not set! Falling back to $TERM"
-    export TERM TTY
+if [[ -z ${TERM-} ]]; then
+    if ! tput &>/dev/null; then
+        case "${TTY:=$(tty)}" in
+        /dev/pts*) export TERM='xterm-256color' ;;
+        *) export TERM=linux ;;
+        esac
+        echo "TERM not set! Falling back to $TERM"
+    fi
 fi
 
 # deactivate virtual environments
-if [ -n "${CONDA_PREFIX:-}" ]; then
+if [[ -n ${CONDA_PREFIX-} ]]; then
+    echo "Deactivating CONDA_PREFIX '$CONDA_PREFIX'"
     conda deactivate
-    echo "CONDA_PREFIX '$CONDA_PREFIX' deactivated"
 fi
-if [ -n "${VIRTUAL_ENV:-}" ]; then
+if [[ -n ${VIRTUAL_ENV-} ]]; then
+    echo "Deactivating VIRTUAL_ENV '$VIRTUAL_ENV'"
     deactivate
-    echo "VIRTUAL_ENV '$VIRTUAL_ENV' deactivated"
 fi
 
 # set paramters that are important for my shell setup
-[ -z "${CURRENT_DISTRO:-}" ] && export CURRENT_DISTRO="$(grep -oP '^NAME="\K[^ ]*' /etc/os-release)"
-export CURRENT_HOSTNAME='iphone'
+export CURRENT_DISTRO="${CURRENT_DISTRO:-$(grep -oP '^NAME="\K[^ ]*' /etc/os-release)}"
+export CURRENT_HOSTNAME='undefined'
 # export CURRENT_DISTRO CURRENT_HOSTNAME
 
-if [ -z "${HOST:-}" ]; then
-    export HOST="$(
-        if command -v hostnamectl >/dev/null 2>&1; then
-            hostnamectl hostname
-        elif [ -f /etc/hostname ]; then
-            cat /etc/hostname
-        fi
-    )"
+if [[ -z ${HOST-} ]]; then
+    if [[ -n ${HOSTNAME-} ]]; then
+        export HOST="$HOSTNAME"
+    elif command -v hostnamectl >/dev/null 2>&1; then
+        export HOST="$(hostnamectl hostname)"
+    elif [[ -f /etc/hostname ]]; then
+        export HOST="$(cat /etc/hostname)"
+    fi
 fi
 export HOSTNAME="${HOSTNAME:-$HOST}"
-export USER="${USER:-$(whoami)}"
+export USER="${USER:-$(whoami || true)}"
 export HOME="${HOME:-/home/$USER}"
+export UID="${UID:-$(id -u "$USER" || true)}"
 
-# set the XDG_RUNTIME_DIR
-if [ -d "${XDG_RUNTIME_DIR:-}" ] && [ -w "${XDG_RUNTIME_DIR:-}" ] && [ -r "${XDG_RUNTIME_DIR:-}" ]; then
-    export XDG_RUNTIME_DIR
-else
-    [ -z "${EUID:-}" ] && export EUID="$(id -u "$USER")"
-    [ -z "${UID:-}" ] && export UID="$EUID"
-    for i in "$UID" "$EUID"; do
-        i="/run/user/$i"
-        if [ -d "$i" ] && [ -w "$i" ] && [ -r "$i" ]; then
-            # must have 0700 access
-            export XDG_RUNTIME_DIR="$i"
-            break
-        fi
-    done
-    # if it failed for whatever reason, then throw an error
-    if [ ! -d "${XDG_RUNTIME_DIR:-}" ]; then
-        # create if it does not exist
-        dir="$XDG_RUNTIME_DIR"
-        dir="${dir%%"${dir##*[!/]}"}"
-        dir="${dir%/*}"
-        dir="${dir%%"${dir##*[!/]}"}"
-        if [ -d "$dir" ] && mkdir "$XDG_RUNTIME_DIR"; then
-            export XDG_RUNTIME_DIR
-        else
-            echo "Error, invalid XDG_RUNTIME_DIR '${XDG_RUNTIME_DIR:-}'!"
-            mkdir "$HOME/.run"
-            export XDG_RUNTIME_DIR="$HOME/.run"
-        fi
-        unset dir
-    fi
-    echo "Set XDG_RUNTIME_DIR to $XDG_RUNTIME_DIR"
-fi
-
-# determine session ID if not set
-if [ -z "${XDG_SESSION_ID:-}" ] || [ -z "${XDG_VTNR:-}" ]; then
-    # who | tr -s ' ' '\t' | cut -f 2
-    # only works with systemd or elogind
-    # TODO: Make this work even in distrobox
-    if command -v loginctl >/dev/null 2>&1; then
-        # respect shell IFS rules
-        [ "${IFS+x}" = x ] && hasifs=1
-        [ "${hasifs:=0}" -eq 1 ] && oldifs="$IFS"
-        IFS="$(printf '\n')"
-        # just get the first match
-        match="$(
-            loginctl list-sessions --no-pager --no-legend | cut -d ' ' -f 1 | while read -r line; do
-                loginctl show-session -p Id -p Active -p TTY "$line" | tr -s '\n' ' '
-                echo
-            done | grep -m 1 -oP "^Id=\K[0-9]+\s*TTY=\S+(?=\s*Active=yes)"
-        )"
-        if [ -z "${XDG_VTNR:-}" ]; then
-            export XDG_VTNR="${match##*tty}"
-            echo "XDG_VTNR was unset! Deriving value to be '$XDG_VTNR'"
-        fi
-        if [ -z "${XDG_SESSION_ID:-}" ]; then
-            export XDG_SESSION_ID="${match%%[[:space:]]*}"
-            echo "XDG_SESSION_ID was unset! Deriving value to be '$XDG_SESSION_ID'"
-        fi
-
-        # restore IFS
-        if [ "${hasifs:=0}" -eq 1 ]; then
-            IFS="$oldifs"
-            unset oldifs
-        else
-            unset IFS
-        fi
-        unset hasifs match
-    fi
-fi
-
+# xdg dirs
 export XDG_CONFIG_HOME="$HOME/.config"
 export XDG_DATA_HOME="$HOME/.local/share"
 export XDG_CACHE_HOME="$HOME/.cache"
 export XDG_STATE_HOME="$HOME/.local/state"
 
-if [ "${EDITOR:-}" != 'nvim' ]; then
+# make them if they don't exist
+if [[ -d $XDG_CONFIG_HOME && -d $XDG_DATA_HOME && -d $XDG_CACHE_HOME && -d $XDG_STATE_HOME ]]; then
+    true
+else
+    while read -r line; do
+        xdg_varname="${line%%=*}"
+        xdg_dirname="${line#*=}"
+        if [[ -d ${xdg_varname-} ]]; then
+            continue
+        elif mkdir -p "$xdg_dirname"; then
+            echo "Created \$$xdg_varname: '$xdg_dirname'"
+        else
+            echo "[1mError, failed to create \$$xdg_varname '$xdg_dirname'[0m"
+            unset "$xdg_varname"
+        fi
+    done <<<"XDG_CONFIG_HOME=$XDG_CONFIG_HOME
+XDG_DATA_HOME=$XDG_DATA_HOME
+XDG_CACHE_HOME=$XDG_CACHE_HOME
+XDG_STATE_HOME=$XDG_STATE_HOME"
+
+    unset line xdg_dirname xdg_varname
+fi
+
+# set important XDG variables
+if [[ -d ${XDG_RUNTIME_DIR-} && -w ${XDG_RUNTIME_DIR-} && -r ${XDG_RUNTIME_DIR-} ]]; then
+    export XDG_RUNTIME_DIR
+else
+    __old_runtime_dir="${XDG_RUNTIME_DIR-}"
+    if [[ -d "/run/user/$UID" && -w "/run/user/$UID" && -r "/run/user/$UID" ]]; then
+        export XDG_RUNTIME_DIR="/run/user/$UID"
+    elif [[ -d /tmp && -w /tmp && -r /tmp ]]; then
+        mkdir "/tmp/fallback_runtime_dir_${USER-}"
+        export XDG_RUNTIME_DIR="/tmp/fallback_runtime_dir_${USER-}"
+    else
+        mkdir "$HOME/.run"
+        export XDG_RUNTIME_DIR="$HOME/.run"
+    fi
+    echo "Error, invalid XDG_RUNTIME_DIR '${__old_runtime_dir}'! Resetting to '$XDG_RUNTIME_DIR'"
+    unset __old_runtime_dir
+fi
+if [[ -z ${XDG_VTNR-} ]]; then
+    XDG_VTNR="$(w -hu | grep -m 1 -oP "^[^\s]*\s*tty\K[0-9]+" || true)"
+    if [[ -n ${XDG_VTNR-} ]]; then
+        export XDG_VTNR
+        echo "Setting XDG_VTNR to $XDG_VTNR"
+    else
+        unset XDG_VTNR
+    fi
+fi
+if [[ -z ${XDG_SESSION_ID-} ]]; then
+    if command -v loginctl &>/dev/null; then
+        XDG_SESSION_ID="$(loginctl list-sessions --no-pager --no-legend | cut -d ' ' -f 1 | xargs loginctl show-session -p Id -p Active | tr '\n' ' ' | grep -oP 'Id=\K[0-9]+(?= Active=yes)' | head -n 1 || true)"
+        # XDG_SESSION_ID="$(loginctl --output=json | jq -r '.[] | select(.state == "active").session' | head -n 1 || true)"
+        if [[ -n ${XDG_SESSION_ID-} ]]; then
+            export XDG_SESSION_ID
+            echo "Setting XDG_SESSION_ID to $XDG_SESSION_ID"
+        else
+            unset XDG_SESSION_ID
+        fi
+    else
+        unset XDG_SESSION_ID
+    fi
+fi
+
+# set LS_COLORS
+if [[ -z ${EXPORTED_LS_COLORS-} || -z ${LS_COLORS-} ]]; then
+    __dircolor_cache="$XDG_RUNTIME_DIR/dircolors.cache"
+    if [[ ! -f "$__dircolor_cache" ]]; then
+        for i in {"${XDG_CONFIG_HOME:=$HOME/.config}",$HOME}/{,.}dir_colors; do
+            if [[ -r $i ]]; then
+                dircolors --sh "$i" >"$__dircolor_cache" && break
+            fi
+        done
+    fi
+    if . "$__dircolor_cache"; then
+        # [[ -n ${ZSH_VERSION-} ]] && type zcompile &>/dev/null && zcompile "$__dircolor_cache"
+        export LS_COLORS
+        [[ -e /etc/profile.d/colorls.sh ]] && export USER_LS_COLORS=true
+        export EXPORTED_LS_COLORS=true
+    else
+        echo "Error loading dircolors cache!"
+    fi
+    unset __dircolor_cache
+fi
+
+if [[ ${EDITOR-} != nvim ]]; then
     # unset EDITOR
-    if command -v nvim >/dev/null; then
+    if command -v nvim &>/dev/null; then
         export EDITOR="nvim"
         export MANPAGER='nvim +Man\!'
     else
         for i in vim hx micro vi nano; do
-            if command -v "$i" >/dev/null 2>&1; then
+            if command -v "$i" &>/dev/null; then
                 export EDITOR="$i"
                 break
             fi
         done
     fi
 fi
-[ -n "${EDITOR:-}" ] && export VISUAL="$EDITOR"
+[[ -n ${EDITOR-} ]] && export VISUAL="$EDITOR"
 export PAGER='less'
 
 if command -v batpipe >/dev/null 2>&1; then
     export LESSOPEN="|/usr/bin/batpipe %s"
     unset LESSCLOSE
-    [ -z "${LESS:-}" ] && export LESS="$LESS -R"
-    export BATPIPE="color"
+    export LESS="${LESS-} -R"
+    export BATPIPE=color
 fi
 
-# TODO: refactor all codium stuff
-export VLK_VSC='/usr/bin/code'
+# export VLK_VSC='/usr/bin/code'
 export TERMINAL='vlk-sensible-terminal 1'
 export BROWSER='vlk-sensible-browser 1'
 export HOMESCRIPTS="$HOME/random/homescripts"
@@ -161,29 +179,14 @@ export ENV="$XDG_CONFIG_HOME/dashrc"
 export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
 export BDOTDIR="$XDG_CONFIG_HOME/bash"
 
-# export LS_PATH="${LS_PATH:-/usr/bin/ls}" WHICH_PATH="${WHICH_PATH:-/usr/bin/which}" RM_PATH="${RM_PATH:=/usr/bin/rm}" VIM_PATH="${VIM_PATH:=/usr/bin/vim}"
-case "${LS_COLORS:-n}" in
-*'xlsx'*) : ;;
-*)
-    if [ -f "${XDG_CONFIG_HOME:=$HOME/.config}/dir_colors" ]; then
-        eval "$(dircolors --sh "$XDG_CONFIG_HOME/dir_colors" || echo 'echo error loading dircolors')"
-    fi
-    ;;
-esac
 # export LESSOPEN="||/usr/bin/lesspipe.sh %s"
-# [ -z "${USER_LS_COLORS:-}" ] && export USER_LS_COLORS="$LS_COLORS"
 
-# eval "$(dircolors --sh "${XDG_CONFIG_HOME:-$HOME/.config}/dir_colors" || echo 'echo error loading dircolors')"
-
-export DIRECTORY_COLOR="${LS_COLORS##*:di=}"
-export DIRECTORY_COLOR="${DIRECTORY_COLOR%%:*}"
 export GREP_COLORS="mt=01;91:fn=03;32:ln=33:bn=36:se=35"
 export JQ_COLORS="0;31:0;36:1;36:0;33:1;32:0;37:1;37"
-VLK_COLOR_REFERENCE="accent=#7a5dfc:accent_l=#af99ff:err=#FF5050:bg=#272B33:"
+# VLK_COLOR_REFERENCE="accent=#7a5dfc:accent_l=#af99ff:err=#FF5050:bg=#272B33:"
 export SUDO_PROMPT="[0;1m[[31mSUDO[0;1m][0m "
 export FZF_DEFAULT_OPTS="--prompt=' ' --pointer=' ' --marker=' ' --tabstop=4 --no-mouse --ansi \
 --color=fg:#ccccdc,hl:#df6b75,fg+:#fcfcff,bg+:#2c323d,hl+:#d682f0,info:#f2ce97,prompt:#d7005f,pointer:#65b6f8,marker:#56b5c2,spinner:#d682f0,header:#e6e6e6 "
-# export LS_COLORS DIRECTORY_COLOR GREP_COLORS JQ_COLORS SUDO_PROMPT FZF_DEFAULT_OPTS
 
 # rofi
 export ROFI_ICON_NORMAL='#e2e4e9'
@@ -198,6 +201,7 @@ export XRESOURCES="$XDG_CONFIG_HOME/X11/Xresources"
 # hists
 export HISTFILE="$XDG_RUNTIME_DIR/shellhist"
 export LESSHISTFILE='/dev/null'
+export MYSQL_HISTFILE="$XDG_DATA_HOME/mysql_history"
 
 # qt customzation
 export QT_QPA_PLATFORMTHEME='qt5ct'
@@ -214,8 +218,10 @@ export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"
 export RXVT_SOCKET="$XDG_RUNTIME_DIR/urxvtd"
 export W3M_DIR="$XDG_STATE_HOME/w3m"
 export MACHINE_STORAGE_PATH="$XDG_DATA_HOME/docker-machine"
-export MYSQL_HISTFILE="$XDG_DATA_HOME/mysql_history"
 export INPUTRC="$XDG_CONFIG_HOME/readline/inputrc"
+export OLLAMA_HOME="$XDG_DATA_HOME/ollama"
+
+# old GTK versions
 export GTK_RC_FILES="$XDG_CONFIG_HOME/gtk-1.0/gtkrc"
 export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
 
@@ -259,96 +265,91 @@ export DENO_INSTALL="$XDG_DATA_HOME/deno"
 
 # keyring
 export GNUPGHOME="$XDG_DATA_HOME/gnupg"
-export GPG_TTY="${TTY:=$(tty)}"
+export GPG_TTY="$TTY"
 export GNOME_KEYRING_CONTROL="${GNOME_KEYRING_CONTROL:-$XDG_RUNTIME_DIR/keyring}"
 export SSH_AUTH_SOCK="${SSH_AUTH_SOCK:-$XDG_RUNTIME_DIR/keyring/ssh}"
 
-export OLLAMA_HOME="$XDG_DATA_HOME/ollama"
-if [ -S "$XDG_RUNTIME_DIR/.ydotool_socket" ]; then
+if [[ -S "$XDG_RUNTIME_DIR/.ydotool_socket" ]]; then
     export YDOTOOL_SOCKET="$XDG_RUNTIME_DIR/.ydotool_socket"
-elif [ -S /tmp/.ydotool_socket ]; then
+elif [[ -S /tmp/.ydotool_socket ]]; then
     export YDOTOOL_SOCKET='/tmp/.ydotool_socket'
 fi
 
-# TODO: skip pathmunge if pathmunge bin doesn't exist. This can cause UB in zsh
-# __vlkenv_pathmunge_bin="$XDG_CONFIG_HOME/shell/rustcfg/pathmunge/target/release/pathmunge"
-__vlkenv_pathmunge_bin="$XDG_CONFIG_HOME/rustcfg/pathmunge/target/release/pathmunge"
-if [ ! -x "$__vlkenv_pathmunge_bin" ]; then
-    if command -v cargo >/dev/null 2>&1; then
-        if expr "$-" : '.*i' >/dev/null; then
-            tgtdir="${__vlkenv_pathmunge_bin%/target*}"
-            lastpath="${PWD:-$(pwd)}"
-            if [ -d "$tgtdir" ]; then
-                builtin cd "$tgtdir" || :
-                cargo build --release
-                builtin cd "$lastpath" || :
-            else
-                echo "vlkenv pathmunge not found. falling back to default."
-            fi
-            unset tgtdir lastpath
-        else
-            echo "Not in interactive mode: Skipping building pathmunge"
-        fi
-    else
-        echo "Cargo not found. Skipping building pathmunge"
-    fi
-    __pathmunge_helper_function() {
-        case ":${pathlike}:" in
-        *":${1}:"*) true ;;
-        *) [ -d "$1" ] && tmppth="$1${tmppth:+:$tmppth}" ;;
-        esac
-    }
+if [[ -n ${BASH_VERSION-} ]]; then
     __pathmunge() {
-        pathlike=''
-        tmppth=''
-        for i in "$@"; do
-            case "${i:-}" in
-            '--pathlike='*)
-                for j in $(echo "${i#*=}" | sed 's/:/ /g'); do
-                    __pathmunge_helper_function "$j"
-                done
-                ;;
-            *)
-                __pathmunge_helper_function "$i"
-                ;;
-            esac
+        local -A __path
+        local hpath
+        local -i idx=0
+        for i in "${dir_pref_before[@]}"; do
+            i="$([[ -d $i ]] && realpath -e "$i" 2>/dev/null)" || continue
+            __path[$i]="$idx:$i"
+            idx+=1
         done
-        echo "$tmppth"
+        while read -r -d ':' i; do
+            i="$([[ -d $i ]] && realpath -e "$i" 2>/dev/null)" || continue
+            if [[ -z ${__path[$i]-} ]]; then
+                __path[$i]="$idx:$i"
+                idx+=1
+            fi
+        done <<<"$INIT_PATH"
+        for i in "${dir_pref_after[@]}"; do
+            i="$([[ -d $i ]] && realpath -e "$i" 2>/dev/null)" || continue
+            __path[$i]="$idx:$i"
+            idx+=1
+        done
+        hpath="$(printf '%s\n' "${__path[@]}" | sort -n | cut -d : -f 2 | tr -s '\n' :)"
+        [[ -z ${essentials-} || ":${hpath-}:" == *":$essentials:"* ]] || hpath="${hpath}:${essentials}"
+        echo "$hpath"
     }
-    __vlkenv_pathmunge_bin='__pathmunge'
+elif [[ -n ${ZSH_VERSION-} ]]; then
+    __pathmunge() {
+        local -aU __path=(${dir_pref_before:A} ${${(s.:.)INIT_PATH}:A})
+        local -aU __zshpath
+        local hpath
+        for i in ${__path:|dir_pref_after} ${dir_pref_after:A}; do
+            [[ -d $i ]] && __zshpath+=($i)
+        done
+        hpath="${(j.:.)__zshpath}"
+        [[ -z ${essentials-} || ":${hpath-}:" == *":$essentials:"* ]] || hpath="${hpath}:${essentials}" #"
+        print "$hpath"
+    }
 fi
 
-export XDG_DATA_DIRS="$(
-    $__vlkenv_pathmunge_bin \
-        "$XDG_DATA_HOME" \
-        "$XDG_DATA_HOME/flatpak/exports/share" \
-        '/var/lib/flatpak/exports/share' \
-        '/usr/local/share' \
-        '/usr/share' \
-        --pathlike="$XDG_DATA_DIRS"
-)"
-export PATH="$(
-    $__vlkenv_pathmunge_bin \
-        "$HOME/bin" \
-        "$HOME/.local/bin" \
-        "${CARGO_HOME:-ch}/bin" \
-        "${GOPATH:-gp}/bin" \
-        "${BUN_INSTALL:-bi}/bin" \
-        "${PNPM_HOME:-ph}" \
-        "${PYTHONUSERBASE:-pu}/bin" \
-        "$XDG_DATA_HOME/flatpak/exports/bin" \
-        '/var/lib/flatpak/exports/bin' \
-        '/usr/local/bin' \
-        --pathlike="$PATH" \
-        '/usr/bin'
-)"
-if [ "${__vlkenv_pathmunge_bin:-}" = '__pathmunge' ]; then
-    unset -f __pathmunge
-    unset -f __pathmunge_helper_function
-fi
-unset oldifs pathlike tmppth i j ICON_TYPE __vlkenv_pathmunge_bin
+typeset -a dir_pref_{before,after}
 
-if [ -n "${VTE_VERSION:-}" ]; then
+dir_pref_before=(
+    "$HOME/"{,.local}/bin
+    {"$CARGO_HOME","$GOPATH","$BUN_INSTALL","$PYTHONUSERBASE"}/bin
+    "$PNPM_HOME"
+    {"$XDG_DATA_HOME",/var/lib}/flatpak/exports/bin
+)
+dir_pref_after=(
+    /usr{/local,}/bin
+    /opt/anaconda/bin
+)
+essentials='/usr/bin'
+INIT_PATH="${PATH-}"
+PATH="$(__pathmunge)"
+
+dir_pref_before=(
+    "$XDG_DATA_HOME"
+    {"$XDG_DATA_HOME",/var/lib}/flatpak/exports/share
+)
+dir_pref_after=(
+    /usr{/local,}/share
+    /opt/anaconda/share
+)
+#essentials='/usr/share'
+# I have zero trust when it comes to this shit
+#essentials='/var/lib/flatpak/exports/share:/usr/local/share:/usr/share'
+essentials=/usr/share
+INIT_PATH="${XDG_DATA_DIRS-}"
+XDG_DATA_DIRS="$(__pathmunge)"
+
+unset i ICON_TYPE dir_pref_{before,after} essentials INIT_PATH
+unset -f __pathmunge
+
+if [[ -n ${VTE_VERSION-} ]]; then
     export ICON_TYPE='dashline'
 else
     case "$TERM" in
diff --git a/bin/vlkenv-old b/bin/vlkenv-old
--- a/bin/vlkenv-old
+++ b/bin/vlkenv-old
@@ -1,191 +1,358 @@
 # shellcheck shell=dash
-# shellcheck disable=2155
+# shellcheck disable=2155,2153
 # vim:foldmethod=marker:ft=sh
+# a script by vlk to load environment variables for sh-compatible shells.
+# Intended to be resilient even if the shell is launched with `env -i`
+
+# unset any safe mode, it is not intended for interactive shells
+set +eu
+# printenv >~/vlkenvcache
+# add /bin to path just in case
+PATH="${PATH:+$PATH:}/usr/bin"
 
 unset MAILCHECK
+[ "${LANG:-C}" = 'C' ] && export LANG="en_US.UTF-8"
 
-[ -n "${CONDA_PREFIX:-}" ] && conda deactivate && echo "\$CONDA_PREFIX '$CONDA_PREFIX' deactivated"
-[ -n "${VIRTUAL_ENV:-}" ] && deactivate && echo "\$VIRTUAL_ENV '$VIRTUAL_ENV' deactivated"
+# set the terminal TERM variable to fix shell behavior
+if [ -z "${TERM:-}" ] || tput 2>&1 | grep -q 'unknown terminal'; then
+    case "${TTY:=$(tty)}" in
+    /dev/pts*) TERM='xterm-256color' ;;
+    *) TERM=linux ;;
+    esac
+    echo "TERM not set! Falling back to $TERM"
+    export TERM TTY
+fi
 
-export CURRENT_DISTRO="$(grep -oP '^NAME="\K[^ ]*' /etc/os-release)"
-export CURRENT_HOSTNAME="Josiah" # The hostname of my main pc
+# deactivate virtual environments
+if [ -n "${CONDA_PREFIX:-}" ]; then
+    conda deactivate
+    echo "CONDA_PREFIX '$CONDA_PREFIX' deactivated"
+fi
+if [ -n "${VIRTUAL_ENV:-}" ]; then
+    deactivate
+    echo "VIRTUAL_ENV '$VIRTUAL_ENV' deactivated"
+fi
 
-export HOME="${HOME:-/home/$(whoami)}"
+# set paramters that are important for my shell setup
+[ -z "${CURRENT_DISTRO:-}" ] && export CURRENT_DISTRO="$(grep -oP '^NAME="\K[^ ]*' /etc/os-release)"
+export CURRENT_HOSTNAME='iphone'
+# export CURRENT_DISTRO CURRENT_HOSTNAME
+
+if [ -z "${HOST:-}" ]; then
+    export HOST="$(
+        if command -v hostnamectl >/dev/null 2>&1; then
+            hostnamectl hostname
+        elif [ -f /etc/hostname ]; then
+            cat /etc/hostname
+        fi
+    )"
+fi
+export HOSTNAME="${HOSTNAME:-$HOST}"
+export USER="${USER:-$(whoami)}"
+export HOME="${HOME:-/home/$USER}"
+
+# set the XDG_RUNTIME_DIR
+if [ -d "${XDG_RUNTIME_DIR:-}" ] && [ -w "${XDG_RUNTIME_DIR:-}" ] && [ -r "${XDG_RUNTIME_DIR:-}" ]; then
+    export XDG_RUNTIME_DIR
+else
+    [ -z "${EUID:-}" ] && export EUID="$(id -u "$USER")"
+    [ -z "${UID:-}" ] && export UID="$EUID"
+    for i in "$UID" "$EUID"; do
+        i="/run/user/$i"
+        if [ -d "$i" ] && [ -w "$i" ] && [ -r "$i" ]; then
+            # must have 0700 access
+            export XDG_RUNTIME_DIR="$i"
+            break
+        fi
+    done
+    # if it failed for whatever reason, then throw an error
+    if [ ! -d "${XDG_RUNTIME_DIR:-}" ]; then
+        # create if it does not exist
+        dir="$XDG_RUNTIME_DIR"
+        dir="${dir%%"${dir##*[!/]}"}"
+        dir="${dir%/*}"
+        dir="${dir%%"${dir##*[!/]}"}"
+        if [ -d "$dir" ] && mkdir "$XDG_RUNTIME_DIR"; then
+            export XDG_RUNTIME_DIR
+        else
+            echo "Error, invalid XDG_RUNTIME_DIR '${XDG_RUNTIME_DIR:-}'!"
+            mkdir "$HOME/.run"
+            export XDG_RUNTIME_DIR="$HOME/.run"
+        fi
+        unset dir
+    fi
+    echo "Set XDG_RUNTIME_DIR to $XDG_RUNTIME_DIR"
+fi
+
+# determine session ID if not set
+if [ -z "${XDG_SESSION_ID:-}" ] || [ -z "${XDG_VTNR:-}" ]; then
+    # who | tr -s ' ' '\t' | cut -f 2
+    # only works with systemd or elogind
+    # TODO: Make this work even in distrobox
+    if command -v loginctl >/dev/null 2>&1; then
+        # respect shell IFS rules
+        [ "${IFS+x}" = x ] && hasifs=1
+        [ "${hasifs:=0}" -eq 1 ] && oldifs="$IFS"
+        IFS="$(printf '\n')"
+        # just get the first match
+        match="$(
+            loginctl list-sessions --no-pager --no-legend | cut -d ' ' -f 1 | while read -r line; do
+                loginctl show-session -p Id -p Active -p TTY "$line" | tr -s '\n' ' '
+                echo
+            done | grep -m 1 -oP "^Id=\K[0-9]+\s*TTY=\S+(?=\s*Active=yes)"
+        )"
+        if [ -z "${XDG_VTNR:-}" ]; then
+            export XDG_VTNR="${match##*tty}"
+            echo "XDG_VTNR was unset! Deriving value to be '$XDG_VTNR'"
+        fi
+        if [ -z "${XDG_SESSION_ID:-}" ]; then
+            export XDG_SESSION_ID="${match%%[[:space:]]*}"
+            echo "XDG_SESSION_ID was unset! Deriving value to be '$XDG_SESSION_ID'"
+        fi
+
+        # restore IFS
+        if [ "${hasifs:=0}" -eq 1 ]; then
+            IFS="$oldifs"
+            unset oldifs
+        else
+            unset IFS
+        fi
+        unset hasifs match
+    fi
+fi
+
 export XDG_CONFIG_HOME="$HOME/.config"
 export XDG_DATA_HOME="$HOME/.local/share"
 export XDG_CACHE_HOME="$HOME/.cache"
 export XDG_STATE_HOME="$HOME/.local/state"
 
-[ -f "$XDG_CONFIG_HOME/user-dirs.dirs" ] && . "$XDG_CONFIG_HOME/user-dirs.dirs"
-export XDG_SCREENSHOTS_DIR="${XDG_PICTURES_DIR:-$HOME/Pictures}/Screenshots"
-
-export EDITOR="nvim"
-export VISUAL="$EDITOR"
+if [ "${EDITOR:-}" != 'nvim' ]; then
+    # unset EDITOR
+    if command -v nvim >/dev/null; then
+        export EDITOR="nvim"
+        export MANPAGER='nvim +Man\!'
+    else
+        for i in vim hx micro vi nano; do
+            if command -v "$i" >/dev/null 2>&1; then
+                export EDITOR="$i"
+                break
+            fi
+        done
+    fi
+fi
+[ -n "${EDITOR:-}" ] && export VISUAL="$EDITOR"
 export PAGER='less'
-export MANPAGER='nvim +Man\!'
+
+if command -v batpipe >/dev/null 2>&1; then
+    export LESSOPEN="|/usr/bin/batpipe %s"
+    unset LESSCLOSE
+    [ -z "${LESS:-}" ] && export LESS="$LESS -R"
+    export BATPIPE="color"
+fi
+
+# TODO: refactor all codium stuff
+export VLK_VSC='/usr/bin/code'
 export TERMINAL='vlk-sensible-terminal 1'
 export BROWSER='vlk-sensible-browser 1'
-
-export QT_QPA_PLATFORMTHEME='qt5ct'
-export QT_STYLE_OVERRIDE='kvantum'
-
-export MOZ_ENABLE_WAYLAND=1
-export UWUFETCH_CACHE_ENABLED=true
-export GTK_USE_PORTAL=1
-
-eval "$(dircolors -b "$XDG_CONFIG_HOME/dircolors/dir_colors" || echo 'echo error loading dircolors')"
-export GREP_COLORS="mt=01;91:fn=03;32:ln=33:bn=36:se=35"
-export JQ_COLORS="0;31:0;36:1;36:0;33:1;32:0;37:1;37"
-export SUDO_PROMPT="$(printf "\e[0m\e[1m[\e[31mSUDO\e[0m\e[1m]\e[0m") "
-
-export ROFI_ICON_NORMAL="#e2e4e9"
-export ROFI_ICON_URGENT="#16181d"
-export ROFI_ICON_ACTIVE="#16181d"
-
 export HOMESCRIPTS="$HOME/random/homescripts"
 
-export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
-export XSERVERRC="$XDG_CONFIG_HOME/X11/xserverrc"
-export XRESOURCES="$XDG_CONFIG_HOME/X11/Xresources"
-#export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
-
+# shell rcfiles
+export ENV="$XDG_CONFIG_HOME/dashrc"
 export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
 export BDOTDIR="$XDG_CONFIG_HOME/bash"
 
-export LESSHISTFILE="/dev/null"
+# export LS_PATH="${LS_PATH:-/usr/bin/ls}" WHICH_PATH="${WHICH_PATH:-/usr/bin/which}" RM_PATH="${RM_PATH:=/usr/bin/rm}" VIM_PATH="${VIM_PATH:=/usr/bin/vim}"
+case "${LS_COLORS:-n}" in
+*'xlsx'*) : ;;
+*)
+    if [ -f "${XDG_CONFIG_HOME:=$HOME/.config}/dir_colors" ]; then
+        eval "$(dircolors --sh "$XDG_CONFIG_HOME/dir_colors" || echo 'echo error loading dircolors')"
+    fi
+    ;;
+esac
+# export LESSOPEN="||/usr/bin/lesspipe.sh %s"
+# [ -z "${USER_LS_COLORS:-}" ] && export USER_LS_COLORS="$LS_COLORS"
+
+# eval "$(dircolors --sh "${XDG_CONFIG_HOME:-$HOME/.config}/dir_colors" || echo 'echo error loading dircolors')"
+
+export DIRECTORY_COLOR="${LS_COLORS##*:di=}"
+export DIRECTORY_COLOR="${DIRECTORY_COLOR%%:*}"
+export GREP_COLORS="mt=01;91:fn=03;32:ln=33:bn=36:se=35"
+export JQ_COLORS="0;31:0;36:1;36:0;33:1;32:0;37:1;37"
+VLK_COLOR_REFERENCE="accent=#7a5dfc:accent_l=#af99ff:err=#FF5050:bg=#272B33:"
+export SUDO_PROMPT="[0;1m[[31mSUDO[0;1m][0m "
+export FZF_DEFAULT_OPTS="--prompt=' ' --pointer=' ' --marker=' ' --tabstop=4 --no-mouse --ansi \
+--color=fg:#ccccdc,hl:#df6b75,fg+:#fcfcff,bg+:#2c323d,hl+:#d682f0,info:#f2ce97,prompt:#d7005f,pointer:#65b6f8,marker:#56b5c2,spinner:#d682f0,header:#e6e6e6 "
+# export LS_COLORS DIRECTORY_COLOR GREP_COLORS JQ_COLORS SUDO_PROMPT FZF_DEFAULT_OPTS
+
+# rofi
+export ROFI_ICON_NORMAL='#e2e4e9'
+export ROFI_ICON_URGENT='#16181d'
+export ROFI_ICON_ACTIVE='#16181d'
+
+# x11
+export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
+export XSERVERRC="$XDG_CONFIG_HOME/X11/xserverrc"
+export XRESOURCES="$XDG_CONFIG_HOME/X11/Xresources"
+
+# hists
+export HISTFILE="$XDG_RUNTIME_DIR/shellhist"
+export LESSHISTFILE='/dev/null'
+
+# qt customzation
+export QT_QPA_PLATFORMTHEME='qt5ct'
+export QT_QPA_PLATFORM_PLUGIN_PATH="$XDG_CONFIG_HOME" #QT_STYLE_OVERRIDE='kvantum'
+
+# wayland
+export MOZ_ENABLE_WAYLAND=1
+export GTK_USE_PORTAL=1
+
+# random xdg shit
+export WINEPREFIX="$XDG_DATA_HOME/wine"
+export DVDCSS_CACHE="$XDG_DATA_HOME/dvdcss"
+export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"
+export RXVT_SOCKET="$XDG_RUNTIME_DIR/urxvtd"
+export W3M_DIR="$XDG_STATE_HOME/w3m"
+export MACHINE_STORAGE_PATH="$XDG_DATA_HOME/docker-machine"
 export MYSQL_HISTFILE="$XDG_DATA_HOME/mysql_history"
-export SHELLHIST="$XDG_RUNTIME_DIR/shellhist"
-export HISTFILE="$SHELLHIST"
+export INPUTRC="$XDG_CONFIG_HOME/readline/inputrc"
+export GTK_RC_FILES="$XDG_CONFIG_HOME/gtk-1.0/gtkrc"
+export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
 
+# java
+export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=\"$XDG_CONFIG_HOME/java\""
+export GRADLE_USER_HOME="$XDG_DATA_HOME/gradle"
+export JAVA_HOME='/usr/lib/jvm/java-17-openjdk-17.0.8.0.7-1.fc38.x86_64'
+export INSTALL4J_JAVA_HOME="${JAVA_HOME:-}"
+
+# perl
+export PERL_CPANM_HOME="$XDG_CACHE_HOME/cpanm"
+
+# rust
+export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
+export CARGO_HOME="$XDG_DATA_HOME/cargo"
+
+# golang
+export GOPATH="$XDG_DATA_HOME/go"
+export GOCACHE="$XDG_CACHE_HOME/go-build"
+export GOMODCACHE="${GOPATH:=$XDG_DATA_HOME/go}/pkg/mod"
+
+# python
+export PYTHONUSERBASE="$XDG_DATA_HOME/python"
+#export PYTHONUSERBASE="$XDG_DATA_HOME/pythonuserbase"
+export PYTHONSTARTUP="$XDG_CONFIG_HOME/pythonrc"
+export PYTHONPYCACHEPREFIX="$XDG_CACHE_HOME/python"
+export PYENV_ROOT="$XDG_DATA_HOME/pyenv"
+export PYTHON_EGG_CACHE="$XDG_CACHE_HOME/python-eggs"
+export WORKON_HOME="$XDG_DATA_HOME/virtualenvs"
+
+# nodejs
+export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
+export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"
+export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
+export NODENV_ROOT="$XDG_DATA_HOME/nodenv"
+export PNPM_HOME="$XDG_DATA_HOME/pnpm"
+export YARN_ENABLE_TELEMETRY=0
+export NVM_DIR="$XDG_DATA_HOME/nvm"
+export BUN_INSTALL="$XDG_DATA_HOME/bun"
+export DENO_INSTALL="$XDG_DATA_HOME/deno"
+
+# keyring
 export GNUPGHOME="$XDG_DATA_HOME/gnupg"
-export GPG_TTY="${TTY:-$(tty)}"
-
+export GPG_TTY="${TTY:=$(tty)}"
 export GNOME_KEYRING_CONTROL="${GNOME_KEYRING_CONTROL:-$XDG_RUNTIME_DIR/keyring}"
 export SSH_AUTH_SOCK="${SSH_AUTH_SOCK:-$XDG_RUNTIME_DIR/keyring/ssh}"
 
-export FZF_DEFAULT_OPTS="--prompt=' ' --pointer=' ' --marker=' ' --tabstop=4 --no-mouse --ansi \
---color=fg:#ccccdc,hl:#df6b75,fg+:#fcfcff,bg+:#2c323d,hl+:#d682f0,info:#f2ce97,prompt:#d7005f,pointer:#65b6f8,marker:#56b5c2,spinner:#d682f0,header:#e6e6e6 "
-
-#export VSCODE_PORTABLE="$XDG_DATA_HOME/vscode"
-
-export WINEPREFIX="$XDG_DATA_HOME/wine"
-
-export DVDCSS_CACHE="$XDG_DATA_HOME/dvdcss"
-
-export RXVT_SOCKET="$XDG_RUNTIME_DIR/urxvtd"
-
+export OLLAMA_HOME="$XDG_DATA_HOME/ollama"
 if [ -S "$XDG_RUNTIME_DIR/.ydotool_socket" ]; then
     export YDOTOOL_SOCKET="$XDG_RUNTIME_DIR/.ydotool_socket"
 elif [ -S /tmp/.ydotool_socket ]; then
     export YDOTOOL_SOCKET='/tmp/.ydotool_socket'
 fi
 
-export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"
-
-export GTK_RC_FILES="$XDG_CONFIG_HOME/gtk-1.0/gtkrc"
-export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
-
-export INPUTRC="$XDG_CONFIG_HOME/readline/inputrc"
-
-export W3M_DIR="$XDG_STATE_HOME/w3m"
-
-#export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
-export MACHINE_STORAGE_PATH="$XDG_DATA_HOME/docker-machine"
-
-export QT_QPA_PLATFORM_PLUGIN_PATH="$XDG_CONFIG_HOME"
-
-export PYTHONSTARTUP="$XDG_CONFIG_HOME/pythonrc"
-export PYTHONPYCACHEPREFIX="$XDG_CACHE_HOME/python"
-export PYTHONUSERBASE="$XDG_DATA_HOME/python"
-export PYENV_ROOT="$XDG_DATA_HOME/pyenv"
-export PYTHON_EGG_CACHE="$XDG_CACHE_HOME/python-eggs"
-export WORKON_HOME="$XDG_DATA_HOME/virtualenvs"
-
-export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=\"$XDG_CONFIG_HOME/java\""
-export GRADLE_USER_HOME="$XDG_DATA_HOME/gradle"
-export JAVA_HOME='/usr/lib/jvm/java-17-openjdk-17.0.8.0.7-1.fc38.x86_64'
-export INSTALL4J_JAVA_HOME="${JAVA_HOME:-}"
-
-export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
-export CARGO_HOME="$XDG_DATA_HOME/cargo"
-
-export GOPATH="$XDG_DATA_HOME/go"
-export GOCACHE="$XDG_CACHE_HOME/go-build"
-export GOMODCACHE="${GOPATH:-$XDG_DATA_HOME/go}/pkg/mod"
-
-export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
-export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"
-export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
-export NODENV_ROOT="$XDG_DATA_HOME/nodenv"
-export PNPM_HOME="$XDG_DATA_HOME/pnpm"
-export NVM_DIR="$XDG_DATA_HOME/nvm"
-export BUN_INSTALL="$XDG_DATA_HOME/bun"
-export DENO_INSTALL="$XDG_DATA_HOME/deno"
-
-__vlkenv_tempdirs="$XDG_DATA_DIRS"
-__vlkenv_terminfodirs=''
-for i in \
-    '/usr/share' \
-    '/usr/local/share' \
-    '/var/lib/flatpak/exports/share' \
-    "$XDG_DATA_HOME/flatpak/exports/share" \
-    "$XDG_DATA_HOME"; do
-    if [ -d "$i" ]; then
-        case ":$__vlkenv_tempdirs:" in
-        *:"$i":*)
-            true
-            ;;
-        *)
-            __vlkenv_tempdirs="$i:$__vlkenv_tempdirs"
-            ;;
+# TODO: skip pathmunge if pathmunge bin doesn't exist. This can cause UB in zsh
+# __vlkenv_pathmunge_bin="$XDG_CONFIG_HOME/shell/rustcfg/pathmunge/target/release/pathmunge"
+__vlkenv_pathmunge_bin="$XDG_CONFIG_HOME/rustcfg/pathmunge/target/release/pathmunge"
+if [ ! -x "$__vlkenv_pathmunge_bin" ]; then
+    if command -v cargo >/dev/null 2>&1; then
+        if expr "$-" : '.*i' >/dev/null; then
+            tgtdir="${__vlkenv_pathmunge_bin%/target*}"
+            lastpath="${PWD:-$(pwd)}"
+            if [ -d "$tgtdir" ]; then
+                builtin cd "$tgtdir" || :
+                cargo build --release
+                builtin cd "$lastpath" || :
+            else
+                echo "vlkenv pathmunge not found. falling back to default."
+            fi
+            unset tgtdir lastpath
+        else
+            echo "Not in interactive mode: Skipping building pathmunge"
+        fi
+    else
+        echo "Cargo not found. Skipping building pathmunge"
+    fi
+    __pathmunge_helper_function() {
+        case ":${pathlike}:" in
+        *":${1}:"*) true ;;
+        *) [ -d "$1" ] && tmppth="$1${tmppth:+:$tmppth}" ;;
         esac
-    fi
-    if [ -d "$i/terminfo" ]; then
-        __vlkenv_terminfodirs="$i/terminfo:$__vlkenv_terminfodirs"
-    fi
-done
-#"$HOME/.var/app/com.valvesoftware.Steam/data" \
-export XDG_DATA_DIRS="$__vlkenv_tempdirs"
-export TERMINFO_DIRS="$__vlkenv_terminfodirs"
+    }
+    __pathmunge() {
+        pathlike=''
+        tmppth=''
+        for i in "$@"; do
+            case "${i:-}" in
+            '--pathlike='*)
+                for j in $(echo "${i#*=}" | sed 's/:/ /g'); do
+                    __pathmunge_helper_function "$j"
+                done
+                ;;
+            *)
+                __pathmunge_helper_function "$i"
+                ;;
+            esac
+        done
+        echo "$tmppth"
+    }
+    __vlkenv_pathmunge_bin='__pathmunge'
+fi
 
-__vlkenv_tempdirs="$PATH"
-for i in \
-    $(echo "$PATH" | sed 's/:/\n/g' | tac) \
-    "/var/lib/flatpak/exports/bin" \
-    "${PYTHONUSERBASE:-PYTHONUSERBASE}/bin" \
-    "${PNPM_HOME:-PNPM_HOME}" \
-    "${BUN_INSTALL:-BUN_INSTALL}/bin" \
-    "${GOPATH:-GOPATH}/bin" \
-    "${CARGO_HOME:-CARGO_HOME}/bin" \
-    "$HOME/.local/bin" \
-    "$HOME/bin"; do
-    if [ -d "$i" ]; then
-        case ":$__vlkenv_tempdirs:" in
-        *:"$i":*)
-            continue
-            ;;
-        *)
-            __vlkenv_tempdirs="$i:$__vlkenv_tempdirs"
-            ;;
-        esac
-    fi
-done
-export PATH="$__vlkenv_tempdirs"
+export XDG_DATA_DIRS="$(
+    $__vlkenv_pathmunge_bin \
+        "$XDG_DATA_HOME" \
+        "$XDG_DATA_HOME/flatpak/exports/share" \
+        '/var/lib/flatpak/exports/share' \
+        '/usr/local/share' \
+        '/usr/share' \
+        --pathlike="$XDG_DATA_DIRS"
+)"
+export PATH="$(
+    $__vlkenv_pathmunge_bin \
+        "$HOME/bin" \
+        "$HOME/.local/bin" \
+        "${CARGO_HOME:-ch}/bin" \
+        "${GOPATH:-gp}/bin" \
+        "${BUN_INSTALL:-bi}/bin" \
+        "${PNPM_HOME:-ph}" \
+        "${PYTHONUSERBASE:-pu}/bin" \
+        "$XDG_DATA_HOME/flatpak/exports/bin" \
+        '/var/lib/flatpak/exports/bin' \
+        '/usr/local/bin' \
+        --pathlike="$PATH" \
+        '/usr/bin'
+)"
+if [ "${__vlkenv_pathmunge_bin:-}" = '__pathmunge' ]; then
+    unset -f __pathmunge
+    unset -f __pathmunge_helper_function
+fi
+unset oldifs pathlike tmppth i j ICON_TYPE __vlkenv_pathmunge_bin
 
-unset ICON_TYPE
-__vlkenv_term="${TERM:-}"
-[ -n "${VTE_VERSION:-}" ] && __vlkenv_term='vte_alacritty'
-case "$__vlkenv_term" in
-*'kitty')
-    ICON_TYPE='dashline'
-    ;;
-*'alacritty'*)
-    ICON_TYPE='powerline'
-    ;;
-*)
-    ICON_TYPE='fallback'
-    ;;
-esac
-export ICON_TYPE
-
-unset i __vlkenv_term __vlkenv_tempdirs __vlkenv_terminfodirs
+if [ -n "${VTE_VERSION:-}" ]; then
+    export ICON_TYPE='dashline'
+else
+    case "$TERM" in
+    *kitty* | *alacritty* | *foot*) export ICON_TYPE='dashline' ;;
+    *) export ICON_TYPE='fallback' ;;
+    esac
+fi
diff --git a/bin/vlkrc b/bin/vlkrc
--- a/bin/vlkrc
+++ b/bin/vlkrc
@@ -85,13 +85,8 @@ alias reboot='systemctl reboot'
 alias logout="loginctl kill-session '$XDG_SESSION_ID'"
 
 alias rmf="$(command which rm) -rf"
-if command -v trash &>/dev/null; then
-    alias rm='trash -i -r'
-else
-    # TODO: make 'better-rm' actually better than rm
-    echo "trash command not installed! falling back to rm"
-    alias rm='rm -ri'
-fi
+#command -v trash &>/dev/null && alias rm='trash -i -r'
+alias rm='better-rm '
 # remove junk files
 for i in "$HOME/".{xsel.log,wget-hsts}; do
     [[ -e "$i" ]] && rmf "$i"
@@ -124,7 +119,8 @@ done
 alias chmodx='chmod +x' chmod-x='chmod -x'
 
 # TODO: Remove ~bin/$, as it is easier to run 'alias \$='''
-alias %="$__homebin/\$"
+# alias %="$__homebin/\$"
+alias {\$,%}=''
 
 alias copy="$__homebin/copy"
 alias copycat="$__homebin/copy --cat"
@@ -141,29 +137,55 @@ alias bap='bat --paging always'
 alias glop='glow --pager'
 alias bat{op,tio,io}=battop
 
-# TODO: migrate to whisper.cpp
-# OpenAI whisper -- run `pip install --user --upgrade --no-deps --force-reinstall git+https://github.com/openai/whisper.git` and `pip install --user blobfile`
-#command -v whisper &>/dev/null && alias whisp='whisper --language en --device cuda --model medium.en --output_format txt'
 alias record='pw-record --target "alsa_input.usb-ASUSTeK_COMPUTER_INC._C-Media_R__Audio-00.analog-stereo" '
 
-whisp() {
+whisp-py() {
+    # designed for use with openai whisper
+    # pip install --user --upgrade --no-deps --force-reinstall git+https://github.com/openai/whisper.git ; pip install --user blobfile
     local -a whispargs=(--language en --device cuda --model medium.en --output_format txt)
     echo "starting whisper with args '${whispargs[*]} $*'"
     whisper "${whispargs[@]}" "$@"
 }
+whisp() {
+    # designed for use with whisper.cpp
+    # https://github.com/ggerganov/whisper.cpp
+    local model="$HOME/random/whisper-cpp/ggml-medium.en.bin"
+    local file="${1-}"
+    file="$(realpath "$file" || :)"
+    local file_base="${file%/*}"
+    if [[ ! -f "$file" ]]; then
+        echo "Error, please input an audio file!"
+        return 1
+    fi
+    if [[ ! -f "${model-}" ]]; then
+        echo "Error, model '${model-}' does not seem to be installed!"
+        return 2
+    fi
+    if [[ ! -w "${file_base-}" ]]; then
+        echo "Error, file basepath '${file_base-}' is not writable!"
+        return 3
+    fi
+    # whisper.cpp is very picky about the wav format
+    local mydir="${XDG_CACHE_HOME:=$HOME/.cache}/whisp"
+    local myfile="$mydir/${file##*/}"
+    local oldpwd="${PWD:=$(pwd)}"
+    (
+        # make temporary cache dir
+        mkdir -p "$mydir"
+        builtin cd "$mydir"
+        # ffmpeg writes new file to temporary output myfile
+        command ffmpeg -i "$file" -acodec pcm_s16le -ar 16000 "$myfile"
+    ) || return
+    local -a whispargs=(--output-txt --print-colors --print-progress --language en --model "$model" -f "$myfile")
+    echo "starting whisper with args '${whispargs[*]} $*'"
+    whisper.cpp "${whispargs[@]}"
+    # remove temporary output file, move all other files
+    command rm "$myfile"
+    command mv -i "$mydir"/* "$file_base"
+    builtin cd "$oldpwd" || return
+    command rm -r "$mydir"
+}
 
-# TODO: just use gpt instead
-if [[ -d "$HOME/src/text-generation-webui" ]]; then
-    llama() {
-        local oldpwd="$PWD"
-        cd "$HOME/src/text-generation-webui" || return 1
-        conda activate textgen
-        python3 ./server.py --chat-buttons --model 'llama-2-13b-chat.Q5_K_M.gguf' --character 'Bob, the real boy'
-        conda deactivate
-        cd "$oldpwd" || return 1
-    }
-    alias textgen=llama
-fi
 #alias llama="cd $HOME/src/text-generation-webui && conda run -vvv -n textgen python ./server.py"
 
 alias download='curl -sfLO '
@@ -177,10 +199,7 @@ else
 fi
 
 alias diff=difft
-# command -v duf &>/dev/null && alias df=duf
-# command -v dutree &>/dev/null && alias du=dutree
-# TODO: make my own extract script
-command -v ouch &>/dev/null && alias extract='ouch decompress'
+# alias extract='ouch decompress'
 
 alias unfuck-old-backup='tar --hole-detection=seek --keep-directory-symlink -xzf '
 
@@ -196,21 +215,11 @@ alias fps='flatpak ps'
 
 alias wget='wget --show-progress'
 
-alias bg-gen='convert +append -resize x1080'
-alias ttymouse='sudo gpm -m /dev/input/mice -t imps2'
-
-# TODO: rename codium script to code
-alias code=codium
+# alias bg-gen='convert +append -resize x1080'
+# alias ttymouse='sudo gpm -m /dev/input/mice -t imps2'
 
 alias {{vi,iv}{m,},v}="$EDITOR"
-alias svim=sudoedit
 
-alias tmuxk='tmux kill-session -t'
-alias tmuxa='tmux attach -t'
-alias tmuxl='tmux list-sessions'
-
-# TODO: in my shell prompt, save and reset stty state after each command
-# Also: run 'cd .' to make sure I'm in the current directory to workaround a bug where removing and recreating a dir with the exact same name as CWD causes UB
 run-subshell() {
     local stty cmd
     [[ -t 0 ]] && stty="$(stty --save)"
@@ -296,7 +305,7 @@ alias flc='flatpak remote-ls --updates'
 
 if command -v pacman &>/dev/null; then
     alias unfuck-pacman-cache="sudo pacman -Qk | grep '[^0] missing files'"
-    alias paci='sudo pacman -S '
+    alias paci='sudo pacman -S --needed '
     alias pacr='sudo pacman -Rcs '
     alias pacl='pacman -Q | fzf'
     alias pacb='pacman -Fl | grep -E "\s+(${PATH//:\//|})" | fzf'
