Commit from shell alias at 09/13/23 02:39:25 PM

diff --git a/bin/vlkrc b/bin/vlkrc
--- a/bin/vlkrc
+++ b/bin/vlkrc
@@ -92,14 +92,14 @@ alias :q=exit
 #     fi
 # }
 
+# alias shutdown='session_end shutdown'
+# alias reboot='session_end reboot'
+# alias restart='session_end reboot'
+# alias logout='session_end logout'
+
 alias shutdown='systemctl poweroff'
 alias reboot='systemctl reboot'
 alias logout="loginctl kill-session '$XDG_SESSION_ID'"
-
-#alias shutdown='session_end shutdown'
-#alias reboot='session_end reboot'
-#alias restart='session_end reboot'
-#alias logout='session_end logout'
 
 __rmcmd="$(which --skip-alias rm)"
 
@@ -279,19 +279,30 @@ alias fenv='printenv | fzf'
 
 alias hr='printf "%*s\n" "${COLUMNS:-$(tput cols)}" "" | tr " " -'
 
+# ___cd_ls() {
+#     builtin cd "$@"
+#     local retval="$?"
+#     ((retval == 0)) || return "$retval"
+#     local -i cdls_max=30
+#     local -i fcount
+#     fcount="$($(which --skip-alias ls) -A1 | wc -l)"
+#     if ((fcount < cdls_max)); then
+#         ls
+#     else
+#         local dir_color="${LS_COLORS:-01;34}"
+#         dir_color="${dir_color##*:di=}"
+#         echo -e "\e[${dir_color%%:*}m${fcount}\e[0m items in this folder"
+#     fi
+# }
+
 if [ -n "${ZSH_VERSION:-}" ]; then
+    # chpwd_functions+=('___cd_ls')
     alias refresh='exec zsh'
-    recompile() {
-        local line
-        recompile.zsh --recompile | while read -r line; do
-            [ ! -f "$line" ] && echo "$line" && continue
-            zcompile "$line"
-        done
-    }
     alias uncompile="recompile.zsh --uncompile"
     alias lsh="hash -dL | sed 's/hash -d //g ; s/=/  \t  /g' | fzf"
 
 elif [ -n "${BASH_VERSION:-}" ]; then
+    # alias cd='___cd_ls'
     alias refresh='exec bash'
 fi
 
@@ -303,6 +314,45 @@ case "${CURRENT_DISTRO:-}" in
     alias grubcfg='sudo grub2-mkconfig -o /etc/grub2.cfg'
     ;;
 esac
+
+mkcd() {
+    local directory="${1:?Error, please choose a directory name!}"
+    directory="$(realpath -m "$directory")"
+    local dircolor="${LS_COLORS##*:di=}"
+    dircolor="${dircolor%%:*}"
+    dircolor="${dircolor:-1;94}"
+
+    if mkdir -p "$directory"; then
+        echo "made dir $directory"
+        cd "$directory" && printf '\033[92m+\033[0m \033[%sm%s\033[0m' "$dircolor" "$directory"
+    else
+        return 1
+    fi
+}
+
+gitc() {
+    local git_link="${1?:Error. Specify link to clone}"
+    local git_dir="$PWD/${git_link##*/}"
+    if [ "$PWD" = "$HOME" ]; then
+        echo "Error: don't clone a git file to '$PWD'!"
+        return 1
+    fi
+    echo -e "Cloning \033[4m$git_link\033[0m "
+    git clone "$git_link"
+    cd "${git_dir%.git}"
+}
+
+readme() {
+    local readmecmd
+    if command -v 'glow' &>/dev/null; then
+        readmecmd='glow'
+    elif command -v 'bat' &>/dev/null; then
+        readmecmd='bat'
+    else
+        readmecmd='cat'
+    fi
+    $readmecmd "$(printf '%s\n' ./* | grep -i 'readme' | fzf --select-1)"
+}
 
 dotadd() {
     local dotfolder="${1:?Error, please choose a folder!}"
